const products = [
  {
    id: 1,
    img: "img/bq1.jpg",
    nameItem: "Biquíni Cortininha Listrado",
    description: "Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 2,
    img: "img/bq2.jpg",
    nameItem: "Biquíni Cortininha Branco",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 3,
    img: "img/bq3.jpg",
    nameItem: "Biquíni Cortininha Amarelo",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 4,
    img: "img/bq4.jpg",
    nameItem: "Biquíni Cortininha Poá",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 5,
    img: "img/bq5.jpg",
    nameItem: "Biquíni Cortininha Preto",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 6,
    img: "img/bq6.jpg",
    nameItem: "Biquíni Top Crochê",
    description:"Em até 2x no cartão sem juros",
    value: 120,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 7,
    img: "img/bq7.jpg",
    nameItem: "Biquíni Top Listrado",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 8,
    img: "img/bq8.jpg",
    nameItem: "Biquíni Meia-Taça Estampado",
    description:"Em até 2x no cartão sem juros",
    value: 110,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 9,
    img: "img/bq9.jpg",
    nameItem: "Biquíni Meia-Taça Preto",
    description:"Em até 2x no cartão sem juros",
    value: 110,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 10,
    img: "img/bq11.jpg",
    nameItem: "Biquíni Top Rosa",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 11,
    img: "img/bq12.jpg",
    nameItem: "Biquíni Meia-Taça Amarelo",
    description:"Em até 2x no cartão sem juros",
    value: 110,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 12,
    img: "img/bq13.jpg",
    nameItem: "Biquíni Cortininha Oncinha",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 13,
    img: "img/bq14.jpg",
    nameItem: "Biquíni Cortininha Rosa Bebê",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 14,
    img: "img/bq15.jpg",
    nameItem: "Biquíni Cortininha Vermelho",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 15,
    img: "img/bq17.jpeg",
    nameItem: "Biquíni Meia-Taça Nude",
    description:"Em até 2x no cartão sem juros",
    value: 110,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 16,
    img: "img/bq18.jpg",
    nameItem: "Biquíni Ciganinha Estampado",
    description:"Em até 2x no cartão sem juros",
    value: 130,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 17,
    img: "img/bq19.jpg",
    nameItem: "Biquíni Cortininha Rosa Bebê",
    description:"Em até 2x no cartão sem juros",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 18,
    img: "img/bq20.jpeg",
    nameItem: "Biquíni Meia-Taça Nude",
    description:"Em até 2x no cartão sem juros",
    value: 110,
    addCart: "Adicionar ao carrinho",
    tag: "Biquínis",
  },
  {
    id: 19,
    img: "img/maio1.png",
    nameItem: "Maiô Meia-Taça Preto",
    description:"Em até 2x no cartão sem juros",
    value: 160,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 20,
    img: "img/maio2.png",
    nameItem: "Maiô Sereia Rosa",
    description:"Em até 2x no cartão sem juros",
    value: 160,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 21,
    img: "img/maio3.png",
    nameItem: "Maiô Cavado Folhagens",
    description:"Em até 2x no cartão sem juros",
    value: 150,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 22,
    img: "img/maio4.png",
    nameItem: "Maiô Cavado Rosa",
    description:"Em até 2x no cartão sem juros",
    value: 150,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 23,
    img: "img/maio5.png",
    nameItem: "Maiô Estampa Psy",
    description:"Em até 2x no cartão sem juros",
    value: 140,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 24,
    img: "img/maio6.png",
    nameItem: "Maiô Decote Rosa",
    description:"Em até 2x no cartão sem juros",
    value: 160,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 25,
    img: "img/maio7.png",
    nameItem: "Maiô Decote Laranja Neon",
    description:"Em até 2x no cartão sem juros",
    value: 160,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 26,
    img: "img/maio8.png",
    nameItem: "Maiô Meia-Taça Folhagens Azul",
    description:"Em até 2x no cartão sem juros",
    value: 140,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 27,
    img: "img/maio9.png",
    nameItem: "Maiô Babado Branco",
    description:"Em até 2x no cartão sem juros",
    value: 160,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 28,
    img: "img/maio10.png",
    nameItem: "Maiô Verde Neon",
    description:"Em até 2x no cartão sem juros",
    value: 140,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 29,
    img: "img/maio11.png",
    nameItem: "Maiô Meia-Taça Azul Royal",
    description:"Em até 2x no cartão sem juros",
    value: 160,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 30,
    img: "img/maio12.png",
    nameItem: "Maiô Azul Ondas",
    description:"Em até 2x no cartão sem juros",
    value: 160,
    addCart: "Adicionar ao carrinho",
    tag: "Maiôs",
  },
  {
    id: 31,
    img: "img/saida1.png",
    nameItem: "Saída de Praia Longa Rendada Branca",
    description:"Em até 2x no cartão sem juros",
    value: 210,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 32,
    img: "img/saida2.png",
    nameItem: "Saída de Praia Branca",
    description:"Em até 2x no cartão sem juros",
    value: 180,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 33,
    img: "img/saida3.png",
    nameItem: "Saída de Praia Saia Branca",
    description:"Em até 2x no cartão sem juros",
    value: 180,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 34,
    img: "img/saida4.png",
    nameItem: "Saída de Praia Nude",
    description:"Em até 2x no cartão sem juros",
    value: 210,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 35,
    img: "img/saida5.png",
    nameItem: "Saída de Praia Camisa Laranja",
    description:"Em até 2x no cartão sem juros",
    value: 170,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 36,
    img: "img/saida6.png",
    nameItem: "Saída de Praia Estampada",
    description:"Em até 2x no cartão sem juros",
    value: 240,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 37,
    img: "img/saida7.png",
    nameItem: "Saída de Praia Renda Curta",
    description:"Em até 2x no cartão sem juros",
    value: 240,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 38,
    img: "img/saida8.png",
    nameItem: "Saída de Praia Crochê Verde",
    description:"Em até 2x no cartão sem juros",
    value: 270,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 39,
    img: "img/saida9.png",
    nameItem: "Saída de Praia Rendada Laranja",
    description:"Em até 2x no cartão sem juros",
    value: 270,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 40,
    img: "img/saida10.png",
    nameItem: "Saída de Praia Ondas Azul",
    description:"Em até 2x no cartão sem juros",
    value: 260,
    addCart: "Adicionar ao carrinho",
    tag: "Saídas",
  },
  {
    id: 41,
    img: "img/plus1.png",
    nameItem: "Biquíni Cortininha Estampado",
    description:"Em até 2x no cartão sem juros",
    value: 120,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
  {
    id: 42,
    img: "img/plus2.png",
    nameItem: "Biquíni Cortininha Verde",
    description:"Em até 2x no cartão sem juros",
    value: 120,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
  {
    id: 43,
    img: "img/plus3.png",
    nameItem: "Biquíni Cortininha Preto Detalhes Neon",
    description:"Em até 2x no cartão sem juros",
    value: 130,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
  {
    id: 44,
    img: "img/plus5.png",
    nameItem: "Biquíni Lacinho Poá",
    description:"Em até 2x no cartão sem juros",
    value: 120,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
  {
    id: 45,
    img: "img/plus7.png",
    nameItem: "Biquíni Alça Larga Azul Royal",
    description:"Em até 2x no cartão sem juros",
    value: 120,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
  {
    id: 46,
    img: "img/plus8.png",
    nameItem: "Biquíni Meia-Taça Rosa",
    description:"Em até 2x no cartão sem juros",
    value: 130,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
  {
    id: 47,
    img: "img/plus9.png",
    nameItem: "Biquíni Cinto Nude",
    description:"Em até 2x no cartão sem juros",
    value: 140,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
  {
    id: 48,
    img: "img/plus14.jpg",
    nameItem: "Biquíni Meia-Taça Estampado",
    description:"Em até 2x no cartão sem juros",
    value: 120,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
  {
    id: 49,
    img: "img/plus16.jpg",
    nameItem: "Biquíni Meia-Taça Listras",
    description:"Em até 2x no cartão sem juros",
    value: 160,
    addCart: "Adicionar ao carrinho",
    tag: "Plus",
  },
];

let listPlus = []
let listSaidas = []
let listMaios = []
let listBiquinis = []
